local rules = {
  "app.soulver.mac",
  "com.adobe.AfterEffects",
  "com.adobe.illustrator",
  "com.adobe.InDesign",
  "com.adobe.Photoshop",
  "com.apple.ActivityMonitor",
  "com.apple.AddressBook",
  "com.apple.airport.airportutility",
  "com.apple.AppStore",
  "com.apple.audio.AudioMIDISetup",
  "com.apple.Automator",
  "com.apple.backup.launcher",
  "com.apple.BluetoothFileExchange",
  "com.apple.bootcampassistant",
  "com.apple.calculator",
  "com.apple.Chess",
  "com.apple.ColorSyncUtility",
  "com.apple.Console",
  "com.apple.Dictionary",
  "com.apple.DigitalColorMeter",
  "com.apple.DiskUtility",
  "com.apple.dt.Xcode",
  "com.apple.FaceTime",
  "com.apple.findmy",
  "com.apple.FontBook",
  "com.apple.grapher",
  "com.apple.Home",
  "com.apple.iBooksX",
  "com.apple.iCal",
  "com.apple.iChat",
  "com.apple.Image_Capture",
  "com.apple.iWork.Keynote",
  "com.apple.iWork.Numbers",
  "com.apple.iWork.Pages",
  "com.apple.keychainaccess",
  "com.apple.Maps",
  "com.apple.MigrateAssistant",
  "com.apple.Music",
  "com.apple.Notes",
  "com.apple.PhotoBooth",
  "com.apple.Photos",
  "com.apple.podcasts",
  "com.apple.QuickTimePlayerX",
  "com.apple.reminders",
  "com.apple.screenshot.launcher",
  "com.apple.ScriptEditor2",
  "com.apple.SFSymbols",
  "com.apple.Stickies",
  "com.apple.stocks",
  "com.apple.systempreferences",
  "com.apple.SystemProfiler",
  "com.apple.Terminal",
  "com.apple.TextEdit",
  "com.apple.TV",
  "com.apple.VoiceMemos",
  "com.apple.VoiceOverUtility",
  "com.bjango.istatmenus",
  "com.colliderli.iina",
  "com.coteditor.CotEditor",
  "com.cryptic-apps.hopper-web-4",
  "com.figma.Desktop",
  "com.giorgiocalderolla.Wipr-Mac",
  "com.groosoft.CommentHere",
  "com.macitbetter.betterzip",
  "com.microsoft.VSCode",
  "com.pfiddlesoft.uibrowser",
  "com.postmanlabs.mac",
  "com.roeybiran.Milonchik",
  "com.samuelmeuli.Glance",
  "com.savantav.truecontrol",
  "com.ScooterSoftware.BeyondCompare",
  "com.sidetree.Translate",
  "com.wolfrosch.Gapplin",
  "de.just-creative.inddPreview",
  "developer.apple.wwdc-Release",
  "io.dictionaries.Dictionaries",
  "me.spaceinbox.Select-Like-A-Boss-For-Safari",
  "net.bluem.pashua",
  "net.freemacsoft.AppCleaner",
  "net.shinyfrog.bear",
  "net.shinyfrog.panda",
  "net.sourceforge.sqlitebrowser",
  "net.televator.Vimari",
  "us.zoom.xos",
  ["at.obdev.LaunchBar.ActionEditor"] = {quit = 0.5, hide = 0.5},
  ["com.apple.iphonesimulator"] = {quit = 1, hide = 0.5},
  ["com.apple.Preview"] = {quit = 1, hide = 0.5},
  ["com.google.Chrome"] = {quit = 4, hide = 1},
  ["com.kapeli.dashdoc"] = {quit = 6, hide = 1},
  ["com.latenightsw.ScriptDebugger7"] = {quit = 1, hide = 0.5},
  ["com.toggl.toggldesktop.TogglDesktop"] = {quit = 8, hide = 0.5},
  ["fr.handbrake.HandBrake"] = {quit = 10, hide = 0.5}
}
return rules
